USE [master]
GO

/****** Object:  Database [LabBaseDatos]    Script Date: 22/11/2020 05:44:56 p. m. ******/
CREATE DATABASE [LabBaseDatos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LabBaseDatos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LabBaseDatos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LabBaseDatos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LabBaseDatos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LabBaseDatos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LabBaseDatos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LabBaseDatos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LabBaseDatos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LabBaseDatos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LabBaseDatos] SET ARITHABORT OFF 
GO

ALTER DATABASE [LabBaseDatos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LabBaseDatos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LabBaseDatos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LabBaseDatos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LabBaseDatos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LabBaseDatos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LabBaseDatos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LabBaseDatos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LabBaseDatos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LabBaseDatos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LabBaseDatos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LabBaseDatos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LabBaseDatos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LabBaseDatos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LabBaseDatos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LabBaseDatos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LabBaseDatos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LabBaseDatos] SET RECOVERY FULL 
GO

ALTER DATABASE [LabBaseDatos] SET  MULTI_USER 
GO

ALTER DATABASE [LabBaseDatos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LabBaseDatos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LabBaseDatos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LabBaseDatos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LabBaseDatos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LabBaseDatos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LabBaseDatos] SET  READ_WRITE 
GO

